# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kolusask/Projects/IDP/3D-Models-engine-in-SDL2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kolusask/Projects/IDP/3D-Models-engine-in-SDL2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kolusask/Projects/IDP/3D-Models-engine-in-SDL2/CMakeFiles /home/kolusask/Projects/IDP/3D-Models-engine-in-SDL2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kolusask/Projects/IDP/3D-Models-engine-in-SDL2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Engine3D

# Build rule for target.
Engine3D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Engine3D
.PHONY : Engine3D

# fast build rule for target.
Engine3D/fast:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/build
.PHONY : Engine3D/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/main.cpp.s
.PHONY : main.cpp.s

src/Component.o: src/Component.cpp.o

.PHONY : src/Component.o

# target to build an object file
src/Component.cpp.o:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Component.cpp.o
.PHONY : src/Component.cpp.o

src/Component.i: src/Component.cpp.i

.PHONY : src/Component.i

# target to preprocess a source file
src/Component.cpp.i:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Component.cpp.i
.PHONY : src/Component.cpp.i

src/Component.s: src/Component.cpp.s

.PHONY : src/Component.s

# target to generate assembly for a file
src/Component.cpp.s:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Component.cpp.s
.PHONY : src/Component.cpp.s

src/Drawable.o: src/Drawable.cpp.o

.PHONY : src/Drawable.o

# target to build an object file
src/Drawable.cpp.o:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Drawable.cpp.o
.PHONY : src/Drawable.cpp.o

src/Drawable.i: src/Drawable.cpp.i

.PHONY : src/Drawable.i

# target to preprocess a source file
src/Drawable.cpp.i:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Drawable.cpp.i
.PHONY : src/Drawable.cpp.i

src/Drawable.s: src/Drawable.cpp.s

.PHONY : src/Drawable.s

# target to generate assembly for a file
src/Drawable.cpp.s:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Drawable.cpp.s
.PHONY : src/Drawable.cpp.s

src/FileReader.o: src/FileReader.cpp.o

.PHONY : src/FileReader.o

# target to build an object file
src/FileReader.cpp.o:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/FileReader.cpp.o
.PHONY : src/FileReader.cpp.o

src/FileReader.i: src/FileReader.cpp.i

.PHONY : src/FileReader.i

# target to preprocess a source file
src/FileReader.cpp.i:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/FileReader.cpp.i
.PHONY : src/FileReader.cpp.i

src/FileReader.s: src/FileReader.cpp.s

.PHONY : src/FileReader.s

# target to generate assembly for a file
src/FileReader.cpp.s:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/FileReader.cpp.s
.PHONY : src/FileReader.cpp.s

src/Line.o: src/Line.cpp.o

.PHONY : src/Line.o

# target to build an object file
src/Line.cpp.o:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Line.cpp.o
.PHONY : src/Line.cpp.o

src/Line.i: src/Line.cpp.i

.PHONY : src/Line.i

# target to preprocess a source file
src/Line.cpp.i:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Line.cpp.i
.PHONY : src/Line.cpp.i

src/Line.s: src/Line.cpp.s

.PHONY : src/Line.s

# target to generate assembly for a file
src/Line.cpp.s:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Line.cpp.s
.PHONY : src/Line.cpp.s

src/Model.o: src/Model.cpp.o

.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i

.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s

.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/Point.o: src/Point.cpp.o

.PHONY : src/Point.o

# target to build an object file
src/Point.cpp.o:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Point.cpp.o
.PHONY : src/Point.cpp.o

src/Point.i: src/Point.cpp.i

.PHONY : src/Point.i

# target to preprocess a source file
src/Point.cpp.i:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Point.cpp.i
.PHONY : src/Point.cpp.i

src/Point.s: src/Point.cpp.s

.PHONY : src/Point.s

# target to generate assembly for a file
src/Point.cpp.s:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Point.cpp.s
.PHONY : src/Point.cpp.s

src/Session.o: src/Session.cpp.o

.PHONY : src/Session.o

# target to build an object file
src/Session.cpp.o:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Session.cpp.o
.PHONY : src/Session.cpp.o

src/Session.i: src/Session.cpp.i

.PHONY : src/Session.i

# target to preprocess a source file
src/Session.cpp.i:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Session.cpp.i
.PHONY : src/Session.cpp.i

src/Session.s: src/Session.cpp.s

.PHONY : src/Session.s

# target to generate assembly for a file
src/Session.cpp.s:
	$(MAKE) -f CMakeFiles/Engine3D.dir/build.make CMakeFiles/Engine3D.dir/src/Session.cpp.s
.PHONY : src/Session.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Engine3D"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Component.o"
	@echo "... src/Component.i"
	@echo "... src/Component.s"
	@echo "... src/Drawable.o"
	@echo "... src/Drawable.i"
	@echo "... src/Drawable.s"
	@echo "... src/FileReader.o"
	@echo "... src/FileReader.i"
	@echo "... src/FileReader.s"
	@echo "... src/Line.o"
	@echo "... src/Line.i"
	@echo "... src/Line.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/Point.o"
	@echo "... src/Point.i"
	@echo "... src/Point.s"
	@echo "... src/Session.o"
	@echo "... src/Session.i"
	@echo "... src/Session.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

